### ISSUE TITLE
Update to current version

### ISSUE THREAD

**Issue by candrews** [flathub/com.bambulab.BambuStudio#2]
This flatpak is at version 1.8.0 Public Beta 2. The current release is 1.8.4: https://github.com/bambulab/BambuStudio/releases

**Comment by hadess** [comment]
> This flatpak is at version 1.8.0 Public Beta 2.

It isn't. It's a newer version from the `master` branch. I need to contact BambuLab so that they explain what branch they use for development, on how they integrate those changes into the stable branches. Right now, this process is a mess, and using the stable branch would require a significant amount of backporting work to even build, let alone function properly.

The [stable 1.8.2 branch](https://github.com/bambulab/BambuStudio/tree/v1.8.2) reports:

> This branch is [106 commits ahead of](https://github.com/bambulab/BambuStudio/compare/master...v1.8.2), [34 commits behind](https://github.com/bambulab/BambuStudio/compare/v1.8.2...master) master.

If you have specific changes that appear in 1.8.4 (and the 1.8.2 branch), and aren't in the Flatpak, please file a new issue with the reference to it.

**Comment by hadess** [comment]
> I need to contact BambuLab so that they explain what branch they use for development, on how they integrate those changes into the stable branches.

Done in https://github.com/bambulab/BambuStudio/issues/3395
